<a href="https://colab.research.google.com/github/justanotheruserhi/ML-OmSU-2022/blob/main/Kariakina%2C%20MIB-001%2C%2006_hw_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
print(np.__version__)

1.21.6


2) Создать нулевой вектор размера 10

In [ ]:
np.linspace(0,0,10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.linspace(7,7,7)

array([7., 7., 7., 7., 7., 7., 7.])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
array = np.linspace(10, 100, 46)
print(array)

[ 10.  12.  14.  16.  18.  20.  22.  24.  26.  28.  30.  32.  34.  36.
  38.  40.  42.  44.  46.  48.  50.  52.  54.  56.  58.  60.  62.  64.
  66.  68.  70.  72.  74.  76.  78.  80.  82.  84.  86.  88.  90.  92.
  94.  96.  98. 100.]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
r = np.random.random_sample(4)
r[::-1]
print(r)

[0.26466449 0.93689044 0.18283631 0.88096521]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
#arr = np.full((4, 4), 7)
#r = np.diag([1, 2, 3, 4])
#r[:4, :4] = arr - должно было слиться, но, видимо, я что-то не так поняла
r = np.full((4, 4), 7)
arr = np.diag([6, 5, 4, 3])
r - arr

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
np.random.randint(0, 4, size = (5, 5))

array([[2, 3, 0, 3, 3],
       [1, 1, 0, 3, 0],
       [0, 2, 3, 3, 3],
       [0, 2, 0, 1, 0],
       [1, 1, 3, 2, 0]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
arr = np.random.randint(9, size = (10,10))
arr - arr.mean(axis = 1, keepdims = True)

array([[ 2.1, -2.9,  3.1, -4.9,  3.1, -0.9,  0.1, -0.9,  2.1, -0.9],
       [ 0.1, -0.9,  2.1, -3.9,  2.1, -2.9,  4.1,  1.1,  2.1, -3.9],
       [ 3.5, -1.5, -2.5, -2.5,  0.5,  0.5, -0.5,  1.5, -0.5,  1.5],
       [ 2. , -4. , -5. , -2. , -2. ,  1. ,  3. ,  3. ,  3. ,  1. ],
       [ 1.1,  0.1, -0.9,  1.1, -4.9,  3.1, -0.9, -3.9,  3.1,  2.1],
       [ 2.1,  1.1,  1.1, -2.9, -2.9, -4.9, -2.9,  3.1,  3.1,  3.1],
       [ 0.5, -1.5,  2.5, -1.5,  2.5, -2.5, -0.5, -2.5,  0.5,  2.5],
       [-1.4,  1.6, -0.4,  3.6, -3.4, -1.4, -2.4, -1.4,  2.6,  2.6],
       [-2.2, -2.2, -3.2,  1.8,  3.8,  0.8,  3.8,  0.8, -3.2, -0.2],
       [-1. ,  3. , -2. , -5. ,  1. ,  1. ,  2. ,  2. ,  1. , -2. ]])

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
arr = np.random.randint(9, size = (10,10))
arr - np.median(arr, axis = 0, keepdims = True)

array([[-4., -1.,  4.,  4.,  0., -4.,  2., -3.,  4., -1.],
       [ 0.,  2., -2.,  4.,  4.,  4.,  2., -2., -2.,  0.],
       [ 3.,  0.,  0., -3., -4., -4., -3., -3.,  1., -3.],
       [ 2., -2.,  4.,  1.,  1.,  2.,  4., -4.,  1., -3.],
       [-3., -3., -1.,  0., -4., -2., -2., -3.,  0.,  0.],
       [ 2., -1.,  0.,  4.,  3., -1.,  4., -1.,  4.,  0.],
       [ 0., -2.,  4., -2., -4.,  3., -2.,  0., -4.,  0.],
       [ 1.,  1.,  4., -3., -1.,  1.,  3.,  3., -4.,  4.],
       [-4.,  1., -3., -3.,  1.,  1.,  4.,  0.,  2., -1.],
       [ 0., -3.,  0.,  2., -4.,  3.,  4., -4.,  4., -4.]])

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
arr = np.random.randint(9, size = (5,5))
max = np.amax(arr, axis = 1, keepdims = True)
min = np.amin(arr, axis = 1, keepdims = True)
np.concatenate((arr, max, min), axis=1)

array([[0, 8, 3, 3, 8, 8, 0],
       [1, 0, 5, 6, 1, 6, 0],
       [2, 2, 2, 4, 3, 4, 2],
       [2, 5, 3, 2, 5, 5, 2],
       [8, 5, 3, 2, 6, 8, 2]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
arr = np.arange(1, 51)
odds = arr[::2].reshape(5,5)
arr = np.arange(2, 51)
evens = arr[::2].reshape(5,5)
mul = np.matmul(odds, evens)
print(mul, "/n")
#inv = np.linalg.inv(mul) - определитель = 0, поэтому не сработает
#print(inv)

[[ 750  800  850  900  950]
 [1850 2000 2150 2300 2450]
 [2950 3200 3450 3700 3950]
 [4050 4400 4750 5100 5450]
 [5150 5600 6050 6500 6950]] /n


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [ ]:
arr = np.zeros((8,8), dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
